os: linux
dist: focal # Ubuntu 20.04 LTS
language: ruby

git:
  depth: 1

env:
  global:
    - BUNDLE_WITHOUT=production
    - BUNDLE_JOBS=3
    - BUNDLE_RETRY=3

jobs:
  fast_finish: true
  include:
    -
      name: "Default"
      rvm: 2.7.6
      gemfile: Gemfile
    -
      name: "Rails 5.2 / Ruby 2.7"
      rvm: 2.7.6
      gemfile: gemfiles/Gemfile.5.2.gemfile
    -
      name: "Rails 6.1 / Ruby 2.7"
      rvm: 2.7.6
      gemfile: gemfiles/Gemfile.6.1.gemfile
    -
      name: "Rails 6.1 / Ruby 3.0"
      rvm: 3.0.3
      gemfile: gemfiles/Gemfile.6.1.gemfile

before_install:
  - gem update --system
  - gem install bundler

install:
  - bundle config set --local deployment 'true'
  - bundler install

before_script:
  - mkdir -p test/tmp

script:
  - bundle exec rake