os: linux
dist: focal # Ubuntu 20.04 LTS
language: ruby

git:
  depth: 1

env:
  global:
    - BUNDLE_WITHOUT=production
    - BUNDLE_JOBS=3
    - BUNDLE_RETRY=3

jobs:
  fast_finish: true
  include:
    -
      name: "Default"
      rvm: 2.7.4
      gemfile: Gemfile
    -
      name: "Rails 4.2 / Ruby 2.7"
      rvm: 2.7.4
      gemfile: gemfiles/Gemfile.4.2-2.7.4

before_install:
  - gem install bundler:1.17.3

install:
  - bundle config set --local deployment 'true'
  - bundler install

before_script:
  - mkdir -p test/tmp

script:
  - bundle exec rake