# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{asset_packager}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Becker", "Brady Bouchard", "Igor Galeta"]
  s.date = %q{2010-12-07}
  s.description = %q{This Rails plugin makes it simple to merge and compress JavaScript and CSS down into one or more files, increasing speed and saving bandwidth}
  s.email = %q{brady@ldawn.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "lib/synthesis.rb",
     "lib/synthesis/asset_package.rb",
     "lib/synthesis/asset_package_helper.rb",
     "lib/synthesis/jsmin.rb",
     "lib/synthesis/railtie.rb",
     "lib/synthesis/version.rb",
     "lib/tasks/asset_packager_tasks.rake"
  ]
  s.homepage = %q{http://synthesis.sbecker.net/pages/asset_packager}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{asset_packager}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{JavaScript and CSS Asset Compression for Production Rails Apps}
  s.test_files = [
    "test/asset_package_helper_development_test.rb",
     "test/asset_packager_test.rb",
     "test/asset_package_helper_production_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

